// <auto-generated />
using System;
using Cineplus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cineplus.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210527014330_SeededTheatersSeatsReproductions")]
    partial class SeededTheatersSeatsReproductions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Cineplus.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Cineplus.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("ntext");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Description = "This movies try to make people laugh.",
                            GenreName = "Comedy"
                        },
                        new
                        {
                            Id = -2,
                            Description = "Guns and guns",
                            GenreName = "Action"
                        });
                });

            modelBuilder.Entity("Cineplus.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Director = "Pedro Pérez",
                            Duration = 134,
                            GenreId = -1,
                            MovieName = "Los 3 de la loma",
                            Score = 7.8000001907348633
                        },
                        new
                        {
                            Id = -2,
                            Director = "Alfredo Jul",
                            Duration = 113,
                            GenreId = -1,
                            MovieName = "Donde cayó la tiza",
                            Score = 9.0
                        },
                        new
                        {
                            Id = -3,
                            Director = "Alain Serdán",
                            Duration = 130,
                            GenreId = -2,
                            MovieName = "Dos es mejor que uno",
                            Score = 0.0
                        });
                });

            modelBuilder.Entity("Cineplus.Models.Reproduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TheaterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("TheaterId");

                    b.ToTable("Reproduction");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            MovieId = -1,
                            StartTime = new DateTime(2021, 5, 26, 21, 43, 29, 653, DateTimeKind.Local).AddTicks(7261),
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -2,
                            MovieId = -1,
                            StartTime = new DateTime(2021, 5, 26, 21, 43, 29, 659, DateTimeKind.Local).AddTicks(2756),
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -3,
                            MovieId = -1,
                            StartTime = new DateTime(2021, 5, 26, 21, 43, 29, 659, DateTimeKind.Local).AddTicks(2815),
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -4,
                            MovieId = -1,
                            StartTime = new DateTime(2021, 5, 26, 21, 43, 29, 659, DateTimeKind.Local).AddTicks(2823),
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -5,
                            MovieId = -1,
                            StartTime = new DateTime(2021, 5, 26, 21, 43, 29, 659, DateTimeKind.Local).AddTicks(2829),
                            TheaterId = -3
                        });
                });

            modelBuilder.Entity("Cineplus.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Column")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Row")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TheaterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TheaterId");

                    b.ToTable("Seat");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Column = 0,
                            Row = 0,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -2,
                            Column = 1,
                            Row = 0,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -3,
                            Column = 2,
                            Row = 0,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -4,
                            Column = 3,
                            Row = 0,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -5,
                            Column = 4,
                            Row = 0,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -6,
                            Column = 5,
                            Row = 0,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -7,
                            Column = 6,
                            Row = 0,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -8,
                            Column = 7,
                            Row = 0,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -9,
                            Column = 8,
                            Row = 0,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -10,
                            Column = 9,
                            Row = 0,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -11,
                            Column = 0,
                            Row = 1,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -12,
                            Column = 1,
                            Row = 1,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -13,
                            Column = 2,
                            Row = 1,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -14,
                            Column = 3,
                            Row = 1,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -15,
                            Column = 4,
                            Row = 1,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -16,
                            Column = 5,
                            Row = 1,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -17,
                            Column = 6,
                            Row = 1,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -18,
                            Column = 7,
                            Row = 1,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -19,
                            Column = 8,
                            Row = 1,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -20,
                            Column = 9,
                            Row = 1,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -21,
                            Column = 0,
                            Row = 2,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -22,
                            Column = 1,
                            Row = 2,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -23,
                            Column = 2,
                            Row = 2,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -24,
                            Column = 3,
                            Row = 2,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -25,
                            Column = 4,
                            Row = 2,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -26,
                            Column = 5,
                            Row = 2,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -27,
                            Column = 6,
                            Row = 2,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -28,
                            Column = 7,
                            Row = 2,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -29,
                            Column = 8,
                            Row = 2,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -30,
                            Column = 9,
                            Row = 2,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -31,
                            Column = 0,
                            Row = 3,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -32,
                            Column = 1,
                            Row = 3,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -33,
                            Column = 2,
                            Row = 3,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -34,
                            Column = 3,
                            Row = 3,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -35,
                            Column = 4,
                            Row = 3,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -36,
                            Column = 5,
                            Row = 3,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -37,
                            Column = 6,
                            Row = 3,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -38,
                            Column = 7,
                            Row = 3,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -39,
                            Column = 8,
                            Row = 3,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -40,
                            Column = 9,
                            Row = 3,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -41,
                            Column = 0,
                            Row = 4,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -42,
                            Column = 1,
                            Row = 4,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -43,
                            Column = 2,
                            Row = 4,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -44,
                            Column = 3,
                            Row = 4,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -45,
                            Column = 4,
                            Row = 4,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -46,
                            Column = 5,
                            Row = 4,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -47,
                            Column = 6,
                            Row = 4,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -48,
                            Column = 7,
                            Row = 4,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -49,
                            Column = 8,
                            Row = 4,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -50,
                            Column = 9,
                            Row = 4,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -51,
                            Column = 0,
                            Row = 5,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -52,
                            Column = 1,
                            Row = 5,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -53,
                            Column = 2,
                            Row = 5,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -54,
                            Column = 3,
                            Row = 5,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -55,
                            Column = 4,
                            Row = 5,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -56,
                            Column = 5,
                            Row = 5,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -57,
                            Column = 6,
                            Row = 5,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -58,
                            Column = 7,
                            Row = 5,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -59,
                            Column = 8,
                            Row = 5,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -60,
                            Column = 9,
                            Row = 5,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -61,
                            Column = 0,
                            Row = 6,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -62,
                            Column = 1,
                            Row = 6,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -63,
                            Column = 2,
                            Row = 6,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -64,
                            Column = 3,
                            Row = 6,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -65,
                            Column = 4,
                            Row = 6,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -66,
                            Column = 5,
                            Row = 6,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -67,
                            Column = 6,
                            Row = 6,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -68,
                            Column = 7,
                            Row = 6,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -69,
                            Column = 8,
                            Row = 6,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -70,
                            Column = 9,
                            Row = 6,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -71,
                            Column = 0,
                            Row = 7,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -72,
                            Column = 1,
                            Row = 7,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -73,
                            Column = 2,
                            Row = 7,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -74,
                            Column = 3,
                            Row = 7,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -75,
                            Column = 4,
                            Row = 7,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -76,
                            Column = 5,
                            Row = 7,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -77,
                            Column = 6,
                            Row = 7,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -78,
                            Column = 7,
                            Row = 7,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -79,
                            Column = 8,
                            Row = 7,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -80,
                            Column = 9,
                            Row = 7,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -81,
                            Column = 0,
                            Row = 8,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -82,
                            Column = 1,
                            Row = 8,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -83,
                            Column = 2,
                            Row = 8,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -84,
                            Column = 3,
                            Row = 8,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -85,
                            Column = 4,
                            Row = 8,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -86,
                            Column = 5,
                            Row = 8,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -87,
                            Column = 6,
                            Row = 8,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -88,
                            Column = 7,
                            Row = 8,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -89,
                            Column = 8,
                            Row = 8,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -90,
                            Column = 9,
                            Row = 8,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -91,
                            Column = 0,
                            Row = 9,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -92,
                            Column = 1,
                            Row = 9,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -93,
                            Column = 2,
                            Row = 9,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -94,
                            Column = 3,
                            Row = 9,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -95,
                            Column = 4,
                            Row = 9,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -96,
                            Column = 5,
                            Row = 9,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -97,
                            Column = 6,
                            Row = 9,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -98,
                            Column = 7,
                            Row = 9,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -99,
                            Column = 8,
                            Row = 9,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -100,
                            Column = 9,
                            Row = 9,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -101,
                            Column = 0,
                            Row = 10,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -102,
                            Column = 1,
                            Row = 10,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -103,
                            Column = 2,
                            Row = 10,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -104,
                            Column = 3,
                            Row = 10,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -105,
                            Column = 4,
                            Row = 10,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -106,
                            Column = 5,
                            Row = 10,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -107,
                            Column = 6,
                            Row = 10,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -108,
                            Column = 7,
                            Row = 10,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -109,
                            Column = 8,
                            Row = 10,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -110,
                            Column = 9,
                            Row = 10,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -111,
                            Column = 0,
                            Row = 11,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -112,
                            Column = 1,
                            Row = 11,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -113,
                            Column = 2,
                            Row = 11,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -114,
                            Column = 3,
                            Row = 11,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -115,
                            Column = 4,
                            Row = 11,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -116,
                            Column = 5,
                            Row = 11,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -117,
                            Column = 6,
                            Row = 11,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -118,
                            Column = 7,
                            Row = 11,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -119,
                            Column = 8,
                            Row = 11,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -120,
                            Column = 9,
                            Row = 11,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -121,
                            Column = 0,
                            Row = 12,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -122,
                            Column = 1,
                            Row = 12,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -123,
                            Column = 2,
                            Row = 12,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -124,
                            Column = 3,
                            Row = 12,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -125,
                            Column = 4,
                            Row = 12,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -126,
                            Column = 5,
                            Row = 12,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -127,
                            Column = 6,
                            Row = 12,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -128,
                            Column = 7,
                            Row = 12,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -129,
                            Column = 8,
                            Row = 12,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -130,
                            Column = 9,
                            Row = 12,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -131,
                            Column = 0,
                            Row = 13,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -132,
                            Column = 1,
                            Row = 13,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -133,
                            Column = 2,
                            Row = 13,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -134,
                            Column = 3,
                            Row = 13,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -135,
                            Column = 4,
                            Row = 13,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -136,
                            Column = 5,
                            Row = 13,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -137,
                            Column = 6,
                            Row = 13,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -138,
                            Column = 7,
                            Row = 13,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -139,
                            Column = 8,
                            Row = 13,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -140,
                            Column = 9,
                            Row = 13,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -141,
                            Column = 0,
                            Row = 14,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -142,
                            Column = 1,
                            Row = 14,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -143,
                            Column = 2,
                            Row = 14,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -144,
                            Column = 3,
                            Row = 14,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -145,
                            Column = 4,
                            Row = 14,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -146,
                            Column = 5,
                            Row = 14,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -147,
                            Column = 6,
                            Row = 14,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -148,
                            Column = 7,
                            Row = 14,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -149,
                            Column = 8,
                            Row = 14,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -150,
                            Column = 9,
                            Row = 14,
                            TheaterId = -1
                        },
                        new
                        {
                            Id = -151,
                            Column = 0,
                            Row = 0,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -152,
                            Column = 1,
                            Row = 0,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -153,
                            Column = 2,
                            Row = 0,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -154,
                            Column = 3,
                            Row = 0,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -155,
                            Column = 4,
                            Row = 0,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -156,
                            Column = 5,
                            Row = 0,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -157,
                            Column = 6,
                            Row = 0,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -158,
                            Column = 7,
                            Row = 0,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -159,
                            Column = 8,
                            Row = 0,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -160,
                            Column = 9,
                            Row = 0,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -161,
                            Column = 0,
                            Row = 1,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -162,
                            Column = 1,
                            Row = 1,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -163,
                            Column = 2,
                            Row = 1,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -164,
                            Column = 3,
                            Row = 1,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -165,
                            Column = 4,
                            Row = 1,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -166,
                            Column = 5,
                            Row = 1,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -167,
                            Column = 6,
                            Row = 1,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -168,
                            Column = 7,
                            Row = 1,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -169,
                            Column = 8,
                            Row = 1,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -170,
                            Column = 9,
                            Row = 1,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -171,
                            Column = 0,
                            Row = 2,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -172,
                            Column = 1,
                            Row = 2,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -173,
                            Column = 2,
                            Row = 2,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -174,
                            Column = 3,
                            Row = 2,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -175,
                            Column = 4,
                            Row = 2,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -176,
                            Column = 5,
                            Row = 2,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -177,
                            Column = 6,
                            Row = 2,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -178,
                            Column = 7,
                            Row = 2,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -179,
                            Column = 8,
                            Row = 2,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -180,
                            Column = 9,
                            Row = 2,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -181,
                            Column = 0,
                            Row = 3,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -182,
                            Column = 1,
                            Row = 3,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -183,
                            Column = 2,
                            Row = 3,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -184,
                            Column = 3,
                            Row = 3,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -185,
                            Column = 4,
                            Row = 3,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -186,
                            Column = 5,
                            Row = 3,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -187,
                            Column = 6,
                            Row = 3,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -188,
                            Column = 7,
                            Row = 3,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -189,
                            Column = 8,
                            Row = 3,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -190,
                            Column = 9,
                            Row = 3,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -191,
                            Column = 0,
                            Row = 4,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -192,
                            Column = 1,
                            Row = 4,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -193,
                            Column = 2,
                            Row = 4,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -194,
                            Column = 3,
                            Row = 4,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -195,
                            Column = 4,
                            Row = 4,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -196,
                            Column = 5,
                            Row = 4,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -197,
                            Column = 6,
                            Row = 4,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -198,
                            Column = 7,
                            Row = 4,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -199,
                            Column = 8,
                            Row = 4,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -200,
                            Column = 9,
                            Row = 4,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -201,
                            Column = 0,
                            Row = 5,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -202,
                            Column = 1,
                            Row = 5,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -203,
                            Column = 2,
                            Row = 5,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -204,
                            Column = 3,
                            Row = 5,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -205,
                            Column = 4,
                            Row = 5,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -206,
                            Column = 5,
                            Row = 5,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -207,
                            Column = 6,
                            Row = 5,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -208,
                            Column = 7,
                            Row = 5,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -209,
                            Column = 8,
                            Row = 5,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -210,
                            Column = 9,
                            Row = 5,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -211,
                            Column = 0,
                            Row = 6,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -212,
                            Column = 1,
                            Row = 6,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -213,
                            Column = 2,
                            Row = 6,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -214,
                            Column = 3,
                            Row = 6,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -215,
                            Column = 4,
                            Row = 6,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -216,
                            Column = 5,
                            Row = 6,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -217,
                            Column = 6,
                            Row = 6,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -218,
                            Column = 7,
                            Row = 6,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -219,
                            Column = 8,
                            Row = 6,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -220,
                            Column = 9,
                            Row = 6,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -221,
                            Column = 0,
                            Row = 7,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -222,
                            Column = 1,
                            Row = 7,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -223,
                            Column = 2,
                            Row = 7,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -224,
                            Column = 3,
                            Row = 7,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -225,
                            Column = 4,
                            Row = 7,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -226,
                            Column = 5,
                            Row = 7,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -227,
                            Column = 6,
                            Row = 7,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -228,
                            Column = 7,
                            Row = 7,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -229,
                            Column = 8,
                            Row = 7,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -230,
                            Column = 9,
                            Row = 7,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -231,
                            Column = 0,
                            Row = 8,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -232,
                            Column = 1,
                            Row = 8,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -233,
                            Column = 2,
                            Row = 8,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -234,
                            Column = 3,
                            Row = 8,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -235,
                            Column = 4,
                            Row = 8,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -236,
                            Column = 5,
                            Row = 8,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -237,
                            Column = 6,
                            Row = 8,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -238,
                            Column = 7,
                            Row = 8,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -239,
                            Column = 8,
                            Row = 8,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -240,
                            Column = 9,
                            Row = 8,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -241,
                            Column = 0,
                            Row = 9,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -242,
                            Column = 1,
                            Row = 9,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -243,
                            Column = 2,
                            Row = 9,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -244,
                            Column = 3,
                            Row = 9,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -245,
                            Column = 4,
                            Row = 9,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -246,
                            Column = 5,
                            Row = 9,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -247,
                            Column = 6,
                            Row = 9,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -248,
                            Column = 7,
                            Row = 9,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -249,
                            Column = 8,
                            Row = 9,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -250,
                            Column = 9,
                            Row = 9,
                            TheaterId = -2
                        },
                        new
                        {
                            Id = -251,
                            Column = 0,
                            Row = 0,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -252,
                            Column = 1,
                            Row = 0,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -253,
                            Column = 2,
                            Row = 0,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -254,
                            Column = 3,
                            Row = 0,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -255,
                            Column = 4,
                            Row = 0,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -256,
                            Column = 0,
                            Row = 1,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -257,
                            Column = 1,
                            Row = 1,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -258,
                            Column = 2,
                            Row = 1,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -259,
                            Column = 3,
                            Row = 1,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -260,
                            Column = 4,
                            Row = 1,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -261,
                            Column = 0,
                            Row = 2,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -262,
                            Column = 1,
                            Row = 2,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -263,
                            Column = 2,
                            Row = 2,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -264,
                            Column = 3,
                            Row = 2,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -265,
                            Column = 4,
                            Row = 2,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -266,
                            Column = 0,
                            Row = 3,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -267,
                            Column = 1,
                            Row = 3,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -268,
                            Column = 2,
                            Row = 3,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -269,
                            Column = 3,
                            Row = 3,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -270,
                            Column = 4,
                            Row = 3,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -271,
                            Column = 0,
                            Row = 4,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -272,
                            Column = 1,
                            Row = 4,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -273,
                            Column = 2,
                            Row = 4,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -274,
                            Column = 3,
                            Row = 4,
                            TheaterId = -3
                        },
                        new
                        {
                            Id = -275,
                            Column = 4,
                            Row = 4,
                            TheaterId = -3
                        });
                });

            modelBuilder.Entity("Cineplus.Models.Theater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Columns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rows")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Theater");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Columns = 10,
                            Rows = 15
                        },
                        new
                        {
                            Id = -2,
                            Columns = 10,
                            Rows = 10
                        },
                        new
                        {
                            Id = -3,
                            Columns = 5,
                            Rows = 5
                        });
                });

            modelBuilder.Entity("Cineplus.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReproductionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReproductionId");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Cineplus.Models.Movie", b =>
                {
                    b.HasOne("Cineplus.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Cineplus.Models.Reproduction", b =>
                {
                    b.HasOne("Cineplus.Models.Movie", "Movie")
                        .WithMany("Reproductions")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cineplus.Models.Theater", "Theater")
                        .WithMany("Reproductions")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("Cineplus.Models.Seat", b =>
                {
                    b.HasOne("Cineplus.Models.Theater", "Theater")
                        .WithMany("Seats")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("Cineplus.Models.Ticket", b =>
                {
                    b.HasOne("Cineplus.Models.Reproduction", "Reproduction")
                        .WithMany("Tickets")
                        .HasForeignKey("ReproductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cineplus.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cineplus.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Reproduction");

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Cineplus.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Cineplus.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cineplus.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Cineplus.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cineplus.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Cineplus.Models.Movie", b =>
                {
                    b.Navigation("Reproductions");
                });

            modelBuilder.Entity("Cineplus.Models.Reproduction", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Cineplus.Models.Theater", b =>
                {
                    b.Navigation("Reproductions");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
